{{- if .Values.lotus.ingressApi.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  {{- with .Values.lotus.ingressApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - {{ .Values.lotus.ingressApi.host }}
    secretName: {{ .Release.Name }}-ingress-tls
  rules:
  - host: {{ .Values.lotus.ingressApi.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-lotus-service
            servicePort: 1234
          path: /{{ .Release.Name }}(/|$)(.*)
{{- end }}
