{{- if .Values.prometheusOperatorServiceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-lotus-service
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: lotus-node-app
      release: {{ .Release.Name }}
  endpoints:
  - port: tcp-api
    path: /debug/metrics
    interval: 30s
{{- end }}
